#!/bin/bash
APP_DIR="$(dirname "${BASH_SOURCE[0]}")"

# echo "Working Directory: $(pwd)"
# echo "App Directory: $(realpath $APP_DIR/main.py)"
# echo "Python Directory: $(realpath $APP_DIR/.venv/bin/python)"

export PYTHONPATH="$APP_DIR${PYTHONPATH:+:$PYTHONPATH}"
exec "$APP_DIR/.venv/bin/python" -m "src.main" "$@"
